# Form implementation generated from reading ui file '/Users/christopherwainwright/Documents/Git Repositories/BSMS/ui/alert.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Alert(object):
    def setupUi(self, Alert):
        Alert.setObjectName("Alert")
        Alert.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Alert.resize(200, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Alert.sizePolicy().hasHeightForWidth())
        Alert.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Alert)
        self.gridLayout.setObjectName("gridLayout")
        self.alertButtons = QtWidgets.QDialogButtonBox(Alert)
        self.alertButtons.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.alertButtons.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.alertButtons.setObjectName("alertButtons")
        self.gridLayout.addWidget(self.alertButtons, 2, 0, 1, 1)
        self.messageLabel = QtWidgets.QLabel(Alert)
        self.messageLabel.setObjectName("messageLabel")
        self.gridLayout.addWidget(self.messageLabel, 1, 0, 1, 1)

        self.retranslateUi(Alert)
        self.alertButtons.accepted.connect(Alert.accept) # type: ignore
        self.alertButtons.rejected.connect(Alert.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Alert)

    def retranslateUi(self, Alert):
        _translate = QtCore.QCoreApplication.translate
        Alert.setWindowTitle(_translate("Alert", "Dialog"))
        self.messageLabel.setText(_translate("Alert", "TextLabel"))
