# Form implementation generated from reading ui file '/Users/christopherwainwright/Documents/Git Repositories/BSMS/ui/new_project.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(375, 165)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.projectNameLabel = QtWidgets.QLabel(Dialog)
        self.projectNameLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.projectNameLabel)
        self.projectNameLineEdit = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projectNameLineEdit.sizePolicy().hasHeightForWidth())
        self.projectNameLineEdit.setSizePolicy(sizePolicy)
        self.projectNameLineEdit.setMinimumSize(QtCore.QSize(250, 25))
        self.projectNameLineEdit.setText("")
        self.projectNameLineEdit.setObjectName("projectNameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.projectNameLineEdit)
        self.songFilepathLabel = QtWidgets.QLabel(Dialog)
        self.songFilepathLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.songFilepathLabel.setObjectName("songFilepathLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.songFilepathLabel)
        self.songFilepathGroup = QtWidgets.QHBoxLayout()
        self.songFilepathGroup.setSpacing(0)
        self.songFilepathGroup.setObjectName("songFilepathGroup")
        self.songFilepathLineEdit = QtWidgets.QLineEdit(Dialog)
        self.songFilepathLineEdit.setMinimumSize(QtCore.QSize(225, 25))
        self.songFilepathLineEdit.setObjectName("songFilepathLineEdit")
        self.songFilepathGroup.addWidget(self.songFilepathLineEdit)
        self.songFilepathSelector = QtWidgets.QToolButton(Dialog)
        self.songFilepathSelector.setMinimumSize(QtCore.QSize(25, 25))
        self.songFilepathSelector.setObjectName("songFilepathSelector")
        self.songFilepathGroup.addWidget(self.songFilepathSelector)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.songFilepathGroup)
        self.imageFilepathLabel = QtWidgets.QLabel(Dialog)
        self.imageFilepathLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.imageFilepathLabel.setObjectName("imageFilepathLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.imageFilepathLabel)
        self.imageFilepathGroup = QtWidgets.QHBoxLayout()
        self.imageFilepathGroup.setSpacing(0)
        self.imageFilepathGroup.setObjectName("imageFilepathGroup")
        self.imageFilepathLineEdit = QtWidgets.QLineEdit(Dialog)
        self.imageFilepathLineEdit.setMinimumSize(QtCore.QSize(225, 25))
        self.imageFilepathLineEdit.setObjectName("imageFilepathLineEdit")
        self.imageFilepathGroup.addWidget(self.imageFilepathLineEdit)
        self.imageFilepathSelector = QtWidgets.QToolButton(Dialog)
        self.imageFilepathSelector.setMinimumSize(QtCore.QSize(25, 25))
        self.imageFilepathSelector.setObjectName("imageFilepathSelector")
        self.imageFilepathGroup.addWidget(self.imageFilepathSelector)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.imageFilepathGroup)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.projectNameLabel.setText(_translate("Dialog", "Project Name"))
        self.songFilepathLabel.setText(_translate("Dialog", "Song Filepath"))
        self.songFilepathSelector.setText(_translate("Dialog", "..."))
        self.imageFilepathLabel.setText(_translate("Dialog", "Image Filepath"))
        self.imageFilepathSelector.setText(_translate("Dialog", "..."))
