# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alert.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Alert(object):
    def setupUi(self, Alert):
        Alert.setObjectName("Alert")
        Alert.setWindowModality(QtCore.Qt.ApplicationModal)
        Alert.resize(200, 150)
        self.gridLayout = QtWidgets.QGridLayout(Alert)
        self.gridLayout.setObjectName("gridLayout")
        self.alertButtons = QtWidgets.QDialogButtonBox(Alert)
        self.alertButtons.setOrientation(QtCore.Qt.Horizontal)
        self.alertButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.alertButtons.setObjectName("alertButtons")
        self.gridLayout.addWidget(self.alertButtons, 2, 0, 1, 1)
        self.messageLabel = QtWidgets.QLabel(Alert)
        self.messageLabel.setObjectName("messageLabel")
        self.gridLayout.addWidget(self.messageLabel, 1, 0, 1, 1)

        self.retranslateUi(Alert)
        self.alertButtons.accepted.connect(Alert.accept)
        self.alertButtons.rejected.connect(Alert.reject)
        QtCore.QMetaObject.connectSlotsByName(Alert)

    def retranslateUi(self, Alert):
        _translate = QtCore.QCoreApplication.translate
        Alert.setWindowTitle(_translate("Alert", "Dialog"))
        self.messageLabel.setText(_translate("Alert", "TextLabel"))
