# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rest_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RestInput(object):
    def setupUi(self, RestInput):
        RestInput.setObjectName("RestInput")
        RestInput.setWindowModality(QtCore.Qt.ApplicationModal)
        RestInput.resize(202, 118)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RestInput.sizePolicy().hasHeightForWidth())
        RestInput.setSizePolicy(sizePolicy)
        self.formLayout = QtWidgets.QFormLayout(RestInput)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(RestInput)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameEdit = QtWidgets.QLineEdit(RestInput)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.durationLabel = QtWidgets.QLabel(RestInput)
        self.durationLabel.setObjectName("durationLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.durationLabel)
        self.buttonBox = QtWidgets.QDialogButtonBox(RestInput)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)
        self.messageLabel = QtWidgets.QLabel(RestInput)
        self.messageLabel.setObjectName("messageLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.messageLabel)
        self.durationSpinBox = QtWidgets.QDoubleSpinBox(RestInput)
        self.durationSpinBox.setObjectName("durationSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.durationSpinBox)

        self.retranslateUi(RestInput)
        self.buttonBox.accepted.connect(RestInput.accept)
        self.buttonBox.rejected.connect(RestInput.reject)
        QtCore.QMetaObject.connectSlotsByName(RestInput)

    def retranslateUi(self, RestInput):
        _translate = QtCore.QCoreApplication.translate
        RestInput.setWindowTitle(_translate("RestInput", "Custom"))
        self.nameLabel.setText(_translate("RestInput", "Name:"))
        self.durationLabel.setText(_translate("RestInput", "Duration:"))
        self.messageLabel.setText(_translate("RestInput", "Input Rest Data:"))
