# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quickstart.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuickstartMenu(object):
    def setupUi(self, QuickstartMenu):
        QuickstartMenu.setObjectName("QuickstartMenu")
        QuickstartMenu.setWindowModality(QtCore.Qt.ApplicationModal)
        QuickstartMenu.resize(500, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QuickstartMenu.sizePolicy().hasHeightForWidth())
        QuickstartMenu.setSizePolicy(sizePolicy)
        QuickstartMenu.setMinimumSize(QtCore.QSize(500, 500))
        QuickstartMenu.setMaximumSize(QtCore.QSize(500, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(QuickstartMenu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.quickstartGroupbox = QtWidgets.QGroupBox(QuickstartMenu)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.quickstartGroupbox.setFont(font)
        self.quickstartGroupbox.setObjectName("quickstartGroupbox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.quickstartGroupbox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newProjectButton = QtWidgets.QPushButton(self.quickstartGroupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newProjectButton.sizePolicy().hasHeightForWidth())
        self.newProjectButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setStrikeOut(False)
        self.newProjectButton.setFont(font)
        self.newProjectButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/general/add"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newProjectButton.setIcon(icon)
        self.newProjectButton.setIconSize(QtCore.QSize(128, 128))
        self.newProjectButton.setObjectName("newProjectButton")
        self.horizontalLayout.addWidget(self.newProjectButton)
        self.openProjectButton = QtWidgets.QPushButton(self.quickstartGroupbox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.openProjectButton.setFont(font)
        self.openProjectButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/folder/not_filled"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/folder/filled"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.openProjectButton.setIcon(icon1)
        self.openProjectButton.setIconSize(QtCore.QSize(128, 128))
        self.openProjectButton.setObjectName("openProjectButton")
        self.horizontalLayout.addWidget(self.openProjectButton)
        self.rhythmEditorButton = QtWidgets.QPushButton(self.quickstartGroupbox)
        self.rhythmEditorButton.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rhythmEditorButton.setFont(font)
        self.rhythmEditorButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/table_edit/not_filled"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/table_edit/filled"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.rhythmEditorButton.setIcon(icon2)
        self.rhythmEditorButton.setIconSize(QtCore.QSize(128, 128))
        self.rhythmEditorButton.setObjectName("rhythmEditorButton")
        self.horizontalLayout.addWidget(self.rhythmEditorButton)
        self.verticalLayout.addWidget(self.quickstartGroupbox)
        self.recentsGroupbox = QtWidgets.QGroupBox(QuickstartMenu)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.recentsGroupbox.setFont(font)
        self.recentsGroupbox.setObjectName("recentsGroupbox")
        self.gridLayout = QtWidgets.QGridLayout(self.recentsGroupbox)
        self.gridLayout.setObjectName("gridLayout")
        self.recentsListWidget = QtWidgets.QListWidget(self.recentsGroupbox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.recentsListWidget.setFont(font)
        self.recentsListWidget.setObjectName("recentsListWidget")
        self.gridLayout.addWidget(self.recentsListWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.recentsGroupbox)

        self.retranslateUi(QuickstartMenu)
        QtCore.QMetaObject.connectSlotsByName(QuickstartMenu)

    def retranslateUi(self, QuickstartMenu):
        _translate = QtCore.QCoreApplication.translate
        QuickstartMenu.setWindowTitle(_translate("QuickstartMenu", "Form"))
        self.quickstartGroupbox.setTitle(_translate("QuickstartMenu", "Quickstart"))
        self.recentsGroupbox.setTitle(_translate("QuickstartMenu", "Recents"))
import ui.resources_rc
